apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  description: This project holds a new frontend app
  sourceRepos: 
    -  https://github.com/Azeezat-git/argocd-project-1.git
  destinations:
    -  namespace: frontend
       server: https://172.31.45.157:33893
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: frontend-admins
      description: Admins for frontend team
      policies:
        - p, proj:frontend-team:frontend-admins, application, *, frontend-team/*, allow
