apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
  finalizers:
    {{- toYaml .Values.argocd.finalizers | nindent 4 }}
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://github.com/Azeezat-git/argocd-project-1.git
    targetRevision: HEAD
    path: kagent/kagent
    helm:
      parameters:
        # Dashboard settings
        - name: dashboard.enabled
          value: "{{ .Values.kagent.dashboard.enabled }}"
        
        # Agents configuration
        {{- range $key, $value := .Values.kagent.agents }}
        - name: agents.{{ $key }}.enabled
          value: "{{ $value.enabled }}"
        {{- end }}
        
        # Tools configuration
        {{- range $key, $value := .Values.kagent.tools }}
        - name: tools.{{ $key }}.enabled
          value: "{{ $value.enabled }}"
        {{- end }}
        
        # Resource limits
        - name: resources.requests.memory
          value: "{{ .Values.kagent.resources.requests.memory }}"
        - name: resources.requests.cpu
          value: "{{ .Values.kagent.resources.requests.cpu }}"
        - name: resources.limits.memory
          value: "{{ .Values.kagent.resources.limits.memory }}"
        - name: resources.limits.cpu
          value: "{{ .Values.kagent.resources.limits.cpu }}"
  destination:
    server: {{ .Values.global.server }}
    namespace: {{ .Values.kagent.namespace }}
  syncPolicy:
    {{- toYaml .Values.argocd.syncPolicy | nindent 4 }}
  revisionHistoryLimit: {{ .Values.argocd.revisionHistoryLimit }}
