apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    {{- toYaml .Values.argocd.finalizers | nindent 4 }}
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://github.com/Azeezat-git/argocd-project-1.git
    targetRevision: HEAD
    path: kagent/kagent-crds
  destination:
    server: {{ .Values.global.server }}
    namespace: default
  syncPolicy:
    {{- toYaml .Values.argocd.syncPolicy | nindent 4 }}
  revisionHistoryLimit: {{ .Values.argocd.revisionHistoryLimit }}
