{{ if .Values.litellm.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: {{ .Values.global.destination.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: {{ .Values.global.project | default "default" }}
  source:
    repoURL: oci://ghcr.io/berriai/litellm-helm
    chart: litellm-helm
    targetRevision: 0.1.802
    helm:
      values: |
        replicaCount: {{ .Values.litellm.replicaCount }}
        
        service:
          type: {{ .Values.litellm.service.type }}
          port: {{ .Values.litellm.service.port }}
        
        resources:
          requests:
            memory: {{ .Values.litellm.resources.requests.memory }}
            cpu: {{ .Values.litellm.resources.requests.cpu }}
          limits:
            memory: {{ .Values.litellm.resources.limits.memory }}
            cpu: {{ .Values.litellm.resources.limits.cpu }}
        
        environmentSecrets:
        {{- range .Values.litellm.environmentSecrets }}
          - {{ . }}
        {{- end }}
        
        proxyConfigMap:
          create: true
          key: config.yaml
        
        db:
          useExisting: {{ .Values.litellm.db.useExisting }}
          deployStandalone: {{ .Values.litellm.db.deployStandalone }}
          endpoint: {{ .Values.litellm.db.endpoint | quote }}
          database: {{ .Values.litellm.db.database | quote }}
          url: {{ .Values.litellm.db.url | quote }}
          secret:
            name: {{ .Values.litellm.db.secret.name | quote }}
            usernameKey: {{ .Values.litellm.db.secret.usernameKey | quote }}
            passwordKey: {{ .Values.litellm.db.secret.passwordKey | quote }}
        
        proxy_config:
          model_list:
          {{- range .Values.litellm.proxy_config.model_list }}
            - model_name: {{ .model_name | quote }}
              litellm_params:
                model: {{ .litellm_params.model | quote }}
                api_key: {{ .litellm_params.api_key | quote }}
                rpm: {{ .litellm_params.rpm }}
                tpm: {{ .litellm_params.tpm }}
          {{- end }}
          
          litellm_settings:
            drop_params: {{ .Values.litellm.proxy_config.litellm_settings.drop_params }}
            set_verbose: {{ .Values.litellm.proxy_config.litellm_settings.set_verbose }}
            callbacks:
            {{- range .Values.litellm.proxy_config.litellm_settings.callbacks }}
              - {{ . | quote }}
            {{- end }}
            prompt_injection_params:
              heuristics_check: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.heuristics_check }}
              similarity_check: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.similarity_check }}
              llm_api_check: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.llm_api_check }}
              llm_api_name: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.llm_api_name | quote }}
              llm_api_system_prompt: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.llm_api_system_prompt | quote }}
              llm_api_fail_call_string: {{ .Values.litellm.proxy_config.litellm_settings.prompt_injection_params.llm_api_fail_call_string | quote }}
          
          general_settings:
            master_key: {{ .Values.litellm.proxy_config.general_settings.master_key | quote }}
            database_url: {{ .Values.litellm.proxy_config.general_settings.database_url | quote }}
            max_parallel_requests: {{ .Values.litellm.proxy_config.general_settings.max_parallel_requests }}
            max_requests_per_minute: {{ .Values.litellm.proxy_config.general_settings.max_requests_per_minute }}
            max_requests_per_hour: {{ .Values.litellm.proxy_config.general_settings.max_requests_per_hour }}
            database_connection_pool_limit: {{ .Values.litellm.proxy_config.general_settings.database_connection_pool_limit }}
            database_connection_timeout: {{ .Values.litellm.proxy_config.general_settings.database_connection_timeout }}
            store_model_in_db: {{ .Values.litellm.proxy_config.general_settings.store_model_in_db }}
            store_prompts_in_spend_logs: {{ .Values.litellm.proxy_config.general_settings.store_prompts_in_spend_logs }}
            key_management_system: {{ .Values.litellm.proxy_config.general_settings.key_management_system | quote }}
            key_management_settings:
              primary_secret_name: {{ .Values.litellm.proxy_config.general_settings.key_management_settings.primary_secret_name | quote }}
              access_mode: {{ .Values.litellm.proxy_config.general_settings.key_management_settings.access_mode | quote }}
              hosted_keys:
              {{- range .Values.litellm.proxy_config.general_settings.key_management_settings.hosted_keys }}
                - {{ . | quote }}
              {{- end }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.litellm.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
