# Global settings
global:
  namespace: kagent
  project: default
  server: https://172.31.45.157:33893 

# Kagent settings
kagent:
  version: "0.6.21"
  namespace: kagent
  
  # Dashboard settings
  dashboard:
    enabled: false
  
  # Agents configuration
  agents:
    k8s-agent:
      enabled: false
    helm-agent:
      enabled: false
    istio-agent:
      enabled: false
    argo-rollouts-agent:
      enabled: false
    cilium-debug-agent:
      enabled: false
    cilium-manager-agent:
      enabled: false
    cilium-policy-agent:
      enabled: false
    kgateway-agent:
      enabled: false
    observability-agent:
      enabled: false
    promql-agent:
      enabled: false
  
  # Tools configuration
  tools:
    grafana-mcp:
      enabled: false
    querydoc:
      enabled: false
  
  # Resource limits
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# ArgoCD settings
argocd:
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
