apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: "bimsol4real@gmail.com"
  email-password: "jxtk qubf ocjh qrel"
