apiVersion: apps/v1
kind: Deployment
metadata:
  name: chai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chai-app
  template:
    metadata:
      labels:
        app: chai-app
    spec:
      containers:
      - name: chai-app
        image: amitabhdevops/chai-app-dev:latest
        ports:
        - containerPort: 8080
        env:
        - name: VITE_GEMINI_API
          valueFrom:
            secretKeyRef:
              name: chai-app-secret
              key: VITE_GEMINI_API
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"