apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Azeezat-git/argocd-project-1.git
    targetRevision: main
    path: app_of_apps/apps
  destination:
    server: https://172.31.45.157:33893
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true

